apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: eemeli-demo
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eemeli-demo
      component: frontend
  template:
    metadata:
      labels:
        app: eemeli-demo
        component: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: REACT_APP_API_URL
          value: "/api"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /nginx-health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /nginx-health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        fsGroup: 1001
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: eemeli-demo
    component: frontend
spec:
  ports:
  - name: frontend-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: eemeli-demo
    component: frontend
  type: ClusterIP
